### ISSUE TITLE
is it really the offical api you support ?

### ISSUE THREAD

**Issue by bbnnt** [uploadcare/uploadcare-ruby#10]
Gemfile :

`gem 'uploadcare-ruby'`

then `bundle install` (obviously)

Console (rails c):

`@api = Uploadcare::Api.new(CONFIG)`

returns 

`NameError: uninitialized constant Uploadcare`

`bundle update`, retrying via the console, nothing better

Not even trying to understand where this CONFIG thing comes from (looked at the previous issues first - this .yml thing to place "anywhere you want" feels weird). 

You might have people willing to pay a cool bunch of dollars every month for your service, but having a gem you can't use straight up from the README might be the last thing to do (in my humble opinion)

Thing is, I'd be still happy to use this tool

Best

**Comment by kalys** [comment]
You have to require library by ```require 'uploadcare'```

CONFIG is Hash with the following keys https://github.com/uploadcare/uploadcare-ruby/blob/master/lib/uploadcare.rb#L9-L16.
