### ISSUE TITLE
`Uploadcare::File#delete` is not deleting the file.

### ISSUE THREAD

**Issue by ricardoperezMTVH** [uploadcare/uploadcare-ruby#118]
### Describe the bug

`Uploadcare::File#delete` is not deleting the file. 

#### Using the doc reference
```ruby 
file = Uploadcare::File.file("FILE_ID_IN_YOUR_PROJECT")
file.detele # return file json, but nothing happens.
```

#### Newly updated images
```ruby
file = File.open(file_path)
uc_file = Uploadcare::Uploader.upload(file)
Uploadcare::File.delete(uc_file.uiid) # don't delete the file
uc.delete # also don't delete the file
```

### Environment

 - Library version: 4
 - Language/framework version: Ruby 3.0.3
 - OS version: MacOs Venture

**Comment by kraft001** [comment]
@ricardoperezMTVH How do you check if the file isn't actually deleted?
I tested the feature on the latest uploadcare-ruby version 4.3.1, and it works fine:

``` ruby
file_to_upload = File.open('test.png')
uc_file = Uploadcare::Uploader.upload(file_to_upload)

puts Uploadcare::File.info(uc_file.uuid).datetime_removed # => blank
Uploadcare::File.delete(uc_file.uuid)
puts Uploadcare::File.info(uc_file.uuid).datetime_removed # => 2023-03-20T18:48:29.416021Z
```

You can also run [the test Rails project](https://github.com/uploadcare/uploadcare-rails-example) on your local env and try to click the "Delete" button there, it works well for me.

**Comment by ricardoperezMTVH** [comment]
@kraft001 I've tested that accessing directly the file on the CDN and listing the from the group. 
I haven't double checked that since the upgrade to the new version.

**Comment by kraft001** [comment]
@ricardoperezMTVH Yes, the file is cached and the CDN copy can be accessed for some time after the main file is removed.
If you want to remove the CDN cached copy as well, then it looks like a feature request

**Comment by rsedykh** [comment]
@ricardoperezMTVH hi. Right now we don't have cache invalidation feature that you can trigger via API. But we can set up a custom cache length for a project. Email us at help@uploadcare.com and mention this conversation to discuss it with my teammates.
