### ISSUE TITLE
Deprecation and warning messages on the latest version.

### ISSUE THREAD

**Issue by ricardoperezMTVH** [uploadcare/uploadcare-ruby#119]
### Describe the bug

Is not a bug per se, but the latest version of the gem is giving me a couple of warning and deprecation messages loading the gem or using the API

* Follow the [installation](https://github.com/uploadcare/uploadcare-ruby#installation) 
* Require the gem
```ruby
[2] pry(main)> require 'uploadcare'
/Users/ricardoperez/.rvm/gems/ruby-3.0.3/gems/api_struct-1.0.5/lib/api_struct/settings.rb:2:in `<module:ApiStruct>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead
```
* Using the API
```ruby
[3] pry(main)> Uploadcare::File.file(UUID)
W, [2023-02-22T16:57:04.953697 #27459]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
```

### Environment

 - Library version: 4.0 (dry-configurable '0.13.0')
 - Language/framework version: 3.0.3 
 - OS version: macOs Ventura

**Comment by kraft001** [comment]
@ricardoperezMTVH Yes, there was an issue with ruby 3+. It's fixed now.
Could you, please, check the new version (4.3) and let me know if it works well for you?

**Comment by ricardoperezMTVH** [comment]
Hi @kraft001 I've upgrade `uploadcare-ruby` to version `4.3` and there warning messages are gone now. Thanks
