### ISSUE TITLE
Use api_struct style of settings

### ISSUE THREAD

**Issue by kraft001** [uploadcare/uploadcare-ruby#123]
### Brief description of the feature and motivation behind it

Gem `api_struct` uses [endpoints](https://github.com/uploadcare/uploadcare-api_struct/blob/master/lib/api_struct/settings.rb#L5) in its configuration, but `uploadcare-ruby` gem overwrites it and introduces [its own way of configuration](https://github.com/uploadcare/uploadcare-ruby/blob/main/lib/uploadcare.rb#L52-L53).

If we don't need to change API root urls, it may be a good idea to switch to the native api_struct configuration style

**Comment by vipulnsward** [comment]
We will move away from this to use generic client architecture, so closing for now.
