### ISSUE TITLE
Show default_effects in file info of group info response

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#129]
Files can be added to the group with some CDN operations. File info _in group info_ shows this operations separately from UUID.

<img width="634" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/f8efbb52-b930-4ab1-a692-35c1c4e785b8">

https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group/operation/groupInfo
https://uploadcare.com/api-refs/upload-api/#tag/Groups/operation/filesGroupInfo

p.s. Don't forget to update uploadcare-rails-example if necessary.

**Comment by vipulnsward** [comment]
default_effects is already shown as part of the files info in group response.
