### ISSUE TITLE
Add latest add-ons

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#130]
- [AWS Rekognition](https://uploadcare.com/docs/intelligence/object-recognition/)
- [AWS Rekognition Moderation](https://uploadcare.com/docs/unsafe-content/)
- [ClamAV](https://uploadcare.com/docs/security/malware-protection/)
- [Remove.bg](https://uploadcare.com/docs/remove-bg/)

p.s. Don't forget to update uploadcare-rails-example.

**Comment by vipulnsward** [comment]
Will prepare for a new release after which it will update uploadcare-rails and uploadcare-rails-example projects.

**Comment by vipulnsward** [comment]
Remaining Add-on examples have been added in https://github.com/uploadcare/uploadcare-rails-example/pull/29 
Closing this issue, will open new ones if anything is missing.
