### ISSUE TITLE
Deprecate PUT /group/{uuid}/storage/

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#131]
It was deprecated.

<img width="868" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/56a7534d-8b27-42c9-81a7-af10a92315f4">

https://uploadcare.com/api-refs/upload-api/#tag/Groups/operation/filesGroupInfo
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group/operation/groupInfo

To store or remove files from a group, query the list of files in it, split the list into chunks of 100 files per chunk and then perform batch file storing or batch file removal for all the chunks.

p.s. Don't forget to update https://github.com/uploadcare/uploadcare-rails-example if necessary.

**Comment by rsedykh** [comment]
Oops. I've meant https://github.com/uploadcare/uploadcare-rails-example

**Comment by vipulnsward** [comment]
Added a soft deprecation warning in this version, will raise or drop allowing this value from entity in future versions

**Comment by vipulnsward** [comment]
Closing this, we can't remove it completely till API removes it, will let the deprecate live and remove it in future
