### ISSUE TITLE
Extra slash in API endpoints

### ISSUE THREAD

**Issue by alxgsv** [uploadcare/uploadcare-ruby#137]
### Describe the bug

When I do `Uploadcare::File.file("2f7f4987-40f1-4e9a-a5dc-3d603b6b00fb")`, library makes request to 
`https://api.uploadcare.com//files/2f7f4987-40f1-4e9a-a5dc-3d603b6b00fb/` instead of
`https://api.uploadcare.com/files/2f7f4987-40f1-4e9a-a5dc-3d603b6b00fb/`

### Expected behavior

Library shouldn't add extra slashes.

### Environment

 - Library version: Latest release

**Comment by vipulnsward** [comment]
I am unable to reproduce this behavior anymore on main branch.  Are you still seeing it? 
If yes, can share example of where you are seeing this?

**Comment by vipulnsward** [comment]
Tried again, and not able to reproduce, please reopen if we see this issue again

**Comment by alxgsv** [comment]
I can confirm that it's not reproducible currently, thank you!
