### ISSUE TITLE
Prepare api-refs x-codeExamples for Ruby

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#143]
Example — https://github.com/uploadcare/uploadcare-php/tree/master/api-samples.

It will be used in https://uploadcare.com/api-refs/upload-api/ and https://uploadcare.com/api-refs/rest-api/ respectively.

**Comment by rsedykh** [comment]
I've already sent you specs.zip.

**Comment by vipulnsward** [comment]
Where are current examples coming in from on these pages- https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/File/operation/filesList ?

**Comment by rsedykh** [comment]
They are generated by ReDoc from our OpenAPI specs. I added them manually as the x-codeSamples.

If you can do something like this https://github.com/uploadcare/uploadcare-php/tree/master/api-samples, I'll copy-n-paste them into our private repo.

**Comment by vipulnsward** [comment]
@rsedykh Added in https://github.com/uploadcare/uploadcare-ruby/pull/169, I will be updating these in follow up as more API changes are being made.

**Comment by rsedykh** [comment]
Maybe I'm not looking at the right place, where it's there?

**Comment by vipulnsward** [comment]
These are here: https://github.com/uploadcare/uploadcare-ruby/tree/main/api_examples
