### ISSUE TITLE
Don't forget to mention https://github.com/uploadcare/uploadcare-ruby/pull/133 in the next release

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#147]

**Comment by vipulnsward** [comment]
I don't see difference https://github.com/uploadcare/uploadcare-ruby/tree/temp and main branch. Did we mean some other branch?

**Comment by rsedykh** [comment]
Hm.. Why have I created this task.. Honestly, I forgot. I guess I was confused by something and what I wanted to do is to tag and release a version with https://github.com/uploadcare/uploadcare-ruby/pull/133 update. I'll rename this task. We can release the version later with some other changes.

**Comment by vipulnsward** [comment]
This is done
