### ISSUE TITLE
Add Document info method

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#176]
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Conversion

**Comment by vipulnsward** [comment]
Closing as this was already added in https://github.com/uploadcare/uploadcare-ruby/pull/169 
@rsedykh let me know if something else is missing, thanks

**Comment by rsedykh** [comment]
Oh that's my fault, sorry. Was going through all libs and accidentally added this issue here too.
