### ISSUE TITLE
Support "complex" authorization.

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/uploadcare-ruby#19]
`Uploadcare.Simple` should be replaced by `Uploadcare` auth scheme:

https://uploadcare.com/documentation/rest/#request

**Comment by vizvamitra** [comment]
Should I left an ability for users to choose an authorization method?

**Comment by dmitry-mukhin** [comment]
`Uploadcare` is superior in any way, so if that leads to code bloating, don't leave `Uploadcare.Simple` at all.
