### ISSUE TITLE
Batch store/delete of files (for API v0.5)

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/uploadcare-ruby#21]

**Comment by vizvamitra** [comment]
It seems that moving to api v0.5 breaks some pagination-related specs so I paused this one until I'll implement #20.

**Comment by dmitry-mukhin** [comment]
can you be more specific?

**Comment by vizvamitra** [comment]
@dmitry-mukhin it was just a note about why I've moved it back to TODO
