### ISSUE TITLE
Support all options for file copying

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/uploadcare-ruby#22]
https://uploadcare.com/documentation/rest/#files-post

Add support for the following args.

- [x] store
- [x] make_public
- [x] pattern

I'd suggest leaving `copy` as is, deprecate it and create two methods that are logically different, although API endpoint is the same: `create_local_copy`, `create_remote_copy`

**Comment by vizvamitra** [comment]
@dmitry-mukhin "local_copy" sounds for me like the file will be copied to my hard drive. I suggest to call them "internal_copy" and "external_copy" or "duplicate/replicate" and "export" (yet it is not an exact duplicate when copying with operations applied).

**Comment by dmitry-mukhin** [comment]
in this context, there's not hard drives so this shouldn't confuse gem users.
I like internal/external though, let me think.

The idea is to use similar naming scheme across all our libs.
