### ISSUE TITLE
Uploading a URL return sometimes an error

### ISSUE THREAD

**Issue by zenati** [uploadcare/uploadcare-ruby#5]
When uploading a URL using `@api.upload 'http://....'`, sometimes I get this error.

```ruby
NoMethodError: undefined method `names' for nil:NilClass
	from /home/user/.rvm/gems/ruby-2.1.3@app/gems/uploadcare-ruby-1.0.5/lib/uploadcare/utils/parser.rb:45:in `parse'
	from /home/user/.rvm/gems/ruby-2.1.3@app/gems/uploadcare-ruby-1.0.5/lib/uploadcare/utils/parser.rb:13:in `parse_file_string'
	from /home/user/.rvm/gems/ruby-2.1.3@app/gems/uploadcare-ruby-1.0.5/lib/uploadcare/resources/file.rb:7:in `initialize'
```
Thanks.

**Comment by balexand** [comment]
This fix isn't in a released version of the gem. [Here's a link to the file in the `v1.0.5` tag](https://github.com/uploadcare/uploadcare-ruby/blob/v1.0.5/lib/uploadcare/api/uploading_api.rb#L68). You can see that it doesn't contain the fix. When I install the latest version from rubygems.org (1.0.5) I also get a version without this fix.

Can someone please release this? 

cc @dmitry-mukhin

**Comment by balexand** [comment]
It looks like #6 was merged into the master branch but isn't in any of the tagged releases.
