### ISSUE TITLE
REQ: Memory Reduction - replace mime-types with mini_mime

### ISSUE THREAD

**Issue by drush** [uploadcare/uploadcare-ruby#61]
BACKGROUND:
Mime-types is a large, memory intensive gem. Example of allocated memory via ```derailed bundle:objects```:
 
```
allocated memory by gem
-----------------------------------
  30106245  activesupport-5.2.1
   6303003  mime-types-3.2.2
   1771271  addressable-2.6.0
   1748528  activerecord-5.2.1
  ...
```

The equivalent functionality can be accomplished without incurring so much memory overhead using mini_mime gem.
 
See this issue on mini_mime for details on how to reduce.  Major projects are already adopting.
https://github.com/discourse/mini_mime/issues/6

**Comment by dmitry-mukhin** [comment]
thanks for the suggestion
