### ISSUE TITLE
uninitialized constant Uploadcare

### ISSUE THREAD

**Issue by ipatovanton** [uploadcare/uploadcare-ruby#69]
When I try to upload image `Uploadcare::Uploader.upload('https://placekitten.com/96/139')`

I get an error:
`uninitialized constant Uploadcare`

Also when I try to add: require 'uploadcare'

I get an error:

> uploadcare-ruby-3.0.5/lib/uploadcare/client/rest_client.rb:12:in `<module:Client>': uninitialized constant Uploadcare::Client::ApiStruct (NameError)

**Comment by dmitry-mukhin** [comment]
have you set your config settings? e.g.:

```
# your_config_initializer_file.rb
Uploadcare.config.public_key = 'demopublickey'
Uploadcare.config.secret_key = 'demoprivatekey'
```

**Comment by dmitry-mukhin** [comment]
If that's so, I agree that we need a more human friendly error message in this case.

**Comment by rudietuesdays** [comment]
Having the same issue, having set my config keys! Thanks for taking a look!

**Comment by dmitry-mukhin** [comment]
Sorry, you've set the keys and still get the error. Correct?

**Comment by rudietuesdays** [comment]
> Having the same issue, having set my config keys! Thanks for taking a look!

Yes, I have set the keys @dmitry-mukhin

**Comment by shyankashani** [comment]
I am having the same problem

**Comment by shyankashani** [comment]
@dmitry-mukhin @rudietuesdays I've figured it out, you have to add this gem: https://github.com/rubygarage/api_struct/

**Comment by dmitry-mukhin** [comment]
@shyankashani `uploadcare-ruby` already depends on `api_struct`, so not sure how that could help.
maybe you bundler wasn't run properly?

**Comment by dmitry-mukhin** [comment]
@rudietuesdays could you also check that you run bundler after gem version upgrade?
thanks!

**Comment by shyankashani** [comment]
@dmitry-mukhin Huh, I'm not sure! I think it was, but it may not have been. Let's see if that works for @rudietuesdays

**Comment by dmitry-mukhin** [comment]
@shyankashani 
`bundle` run should install all explicit and implicit dependencies, and `api-struct` is [a dependency](https://github.com/uploadcare/uploadcare-ruby/blob/bbb2252a1f502406a57f1a3504ef1cd7c70f36ec/uploadcare-ruby.gemspec#L40)

**Comment by maysam** [comment]
setting ENV variables should be enough and running `Uploadcare.config.public_key` in the console causes error.

something is not right

**Comment by dmitrijivanchenko** [comment]
You should place `require 'uploadcare'` in a file where you use this gem. Problem with `unitialized constant ApiStruct` must be fixed in the branch `feature/1-new-entity-attrs`. We are working on a new version. It is coming soon. For now, you can use the branch `feature/1-new-entity-attrs`.
