### ISSUE TITLE
API KEY?

### ISSUE THREAD

**Issue by fabdelgado** [uploadcare/uploadcare-ruby#7]
where it is placed in Ruby on Rails API KEY?

**Comment by dmitry-mukhin** [comment]
in `CONFIG`: https://github.com/uploadcare/uploadcare-ruby#initalizations

**Comment by fabdelgado** [comment]
@dmitry-mukhin  CONFIG where this defined?

**Comment by fabdelgado** [comment]
Sorry, where define key and private key.

**Comment by dmitry-mukhin** [comment]
wherever you like it.

here you can see [default settings](https://github.com/uploadcare/uploadcare-ruby/blob/master/lib/uploadcare.rb)
when you initiate Api, you may provide config object overriding any of default settings, including API keys:

```
@api = Uploadcare::Api.new({
      public_key: 'yourpublickey',
      private_key: 'yoursecretkey'
})

```

**Comment by fabdelgado** [comment]
ok, thankyou
