### ISSUE TITLE
Trying to upload from ruby on rails 

### ISSUE THREAD

**Issue by fabdelgado** [uploadcare/uploadcare-ruby#8]
Trying to upload from ruby on rails 

  	@api = Uploadcare::Api.new({
      public_key: 'xxxxx',
 
	      private_key: 'xxxxxxxxx'

})
  @api.upload('uploads/panda-rojo.jpg')

Return is : undefined method `default_settings' for Uploadcare:Module

**Comment by luyzdeleon** [comment]
Experiencing the same issue.

**Comment by dmitry-mukhin** [comment]
@romanonthego please take a look

**Comment by TangRufus** [comment]
any news?

**Comment by dmitry-mukhin** [comment]
this happens when you don't define a default_settings, as the error says :)

**Comment by bbnnt** [comment]
sorry to say, still unobvious to understand where/how those settings.yml are stored
