### ISSUE TITLE
Dry configurable update

### ISSUE THREAD

**Issue by skliask** [uploadcare/uploadcare-ruby#97]
### Issue with Dry Configurable

In ruby 3.1 there is this error:
`[dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead`

These warnings are probably present because the version of dry-configurable gem that is used, has seen plenty of updates. Possibly an update would fix it.

Not a major issue for the time being, but it polutes the log with many warnings. After the deprecation though, it will render it unusable.

### Environment

 - Library version: ruby 3.1.2
 - Language/framework version: Rails 7
 - OS version: macOS 12.4

**Comment by mykhi** [comment]
Same issue when upgrading from ruby 2.4.5 to 2.7.6, so it's not just a 3.x thing.
